export default {
    CHECKOUT_REQUEST: 'CHECKOUT_REQUEST',
    CHECKOUT_SUCCESS: 'CHECKOUT_SUCCESS',
    CHECKOUT_FAILURE: 'CHECKOUT_FAILURE',
    RECEIVE_BOOKS: 'RECEIVE_BOOKS',
    ADD_TO_CART: 'ADD_TO_CART',
}

